export * from "./Categoria/args";
export * from "./Estado/args";
export * from "./Marca/args";
export * from "./Origen/args";
export * from "./PrecioAlmacen/args";
export * from "./PrecioVenta/args";
export * from "./Producto/args";
export * from "./Sede/args";
export * from "./Subcategoria/args";
